/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.foursys.locadora.view;

import br.com.foursys.locadora.controller.LocacaoController;

/**
 *
 * @author amendes
 */
public class LocacaoView extends javax.swing.JFrame {
    
    LocacaoController locacaoController = new LocacaoController(LocacaoView.this);
    /**
     * Creates new form LocacaoView
     */
    public LocacaoView() {
        initComponents();
        setLocationRelativeTo(null);
        this.locacaoController.carregarComboCliente();
        this.locacaoController.carregarComboFilme();
        this.locacaoController.carregarComboVendedor();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JcbFilme = new javax.swing.JComboBox();
        JcbVendedor = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        JcbCliente = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLocacao = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JtfValorTotal = new javax.swing.JTextField();
        JtfValorPago = new javax.swing.JTextField();
        JtfTroco = new javax.swing.JTextField();
        JbtSalvar = new javax.swing.JButton();
        JbtSair = new javax.swing.JButton();
        JbtCancelar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JrbCheque = new javax.swing.JRadioButton();
        JrbCredito = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        JrbDebito = new javax.swing.JRadioButton();
        JrbDinheiro = new javax.swing.JRadioButton();
        JbtIncluir = new javax.swing.JButton();
        JbtExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Locação");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Vendedor:");

        jLabel3.setText("Filme:");

        JcbFilme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecione Filme-" }));

        JcbVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecione Vendedor-" }));

        jLabel1.setText("Cliente:");

        JcbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecione Cliente-" }));
        JcbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbClienteActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor", "Promoção", "Valor Promoção"
            }
        ));
        jScrollPane1.setViewportView(tabelaLocacao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Valor Total:");

        jLabel5.setText("Valor pago:");

        jLabel6.setText("Troco:");

        JtfValorTotal.setEditable(false);

        JtfValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JtfValorPagoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JtfValorPagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtfValorPagoKeyTyped(evt);
            }
        });

        JtfTroco.setEditable(false);
        JtfTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfTrocoActionPerformed(evt);
            }
        });
        JtfTroco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JtfTrocoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JtfValorPago, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JtfValorTotal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JtfTroco, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JtfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JtfValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JtfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JbtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/foursys/locadora/view/icons/salvar.png"))); // NOI18N
        JbtSalvar.setText("Salvar");
        JbtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtSalvarActionPerformed(evt);
            }
        });

        JbtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/foursys/locadora/view/icons/sair.png"))); // NOI18N
        JbtSair.setText("Sair");
        JbtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtSairActionPerformed(evt);
            }
        });

        JbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/foursys/locadora/view/icons/cancelar.png"))); // NOI18N
        JbtCancelar.setText("Cancelar");
        JbtCancelar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JbtCancelarFocusGained(evt);
            }
        });
        JbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtCancelarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(JrbCheque);
        JrbCheque.setText("Cheque");
        JrbCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JrbChequeActionPerformed(evt);
            }
        });

        buttonGroup1.add(JrbCredito);
        JrbCredito.setText("Credito");

        jLabel7.setText("Forma de Pagamento:");

        buttonGroup1.add(JrbDebito);
        JrbDebito.setText("Debito");

        buttonGroup1.add(JrbDinheiro);
        JrbDinheiro.setText("Dinheiro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JrbDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JrbCheque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JrbDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JrbCredito)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JrbDinheiro)
                    .addComponent(JrbCredito)
                    .addComponent(JrbDebito)
                    .addComponent(JrbCheque))
                .addContainerGap())
        );

        JbtIncluir.setText("Incluir");
        JbtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtIncluirActionPerformed(evt);
            }
        });

        JbtExcluir.setText("Excluir");
        JbtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JcbFilme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(JbtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JbtSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JcbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JcbFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbtIncluir)
                    .addComponent(JbtExcluir))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JbtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JcbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbClienteActionPerformed

    private void JbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtCancelarActionPerformed

    private void JbtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtSalvarActionPerformed
       this.locacaoController.acaoBotaoSalvar();
    }//GEN-LAST:event_JbtSalvarActionPerformed

    private void JbtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtSairActionPerformed
        dispose();
    }//GEN-LAST:event_JbtSairActionPerformed

    private void JrbChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JrbChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JrbChequeActionPerformed

    private void JbtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtIncluirActionPerformed
        this.locacaoController.incluirFilme();
    }//GEN-LAST:event_JbtIncluirActionPerformed

    private void JbtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtExcluirActionPerformed
       this.locacaoController.excluirFilme();
    }//GEN-LAST:event_JbtExcluirActionPerformed

    private void JtfTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfTrocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfTrocoActionPerformed

    private void JtfTrocoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfTrocoKeyTyped
      
    }//GEN-LAST:event_JtfTrocoKeyTyped

    private void JtfValorPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfValorPagoKeyTyped
        
    }//GEN-LAST:event_JtfValorPagoKeyTyped

    private void JtfValorPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfValorPagoKeyPressed
        
    }//GEN-LAST:event_JtfValorPagoKeyPressed

    private void JtfValorPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JtfValorPagoKeyReleased
       this.locacaoController.troco(evt);
    }//GEN-LAST:event_JtfValorPagoKeyReleased

    private void JbtCancelarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JbtCancelarFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_JbtCancelarFocusGained

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtCancelar;
    private javax.swing.JButton JbtExcluir;
    private javax.swing.JButton JbtIncluir;
    private javax.swing.JButton JbtSair;
    private javax.swing.JButton JbtSalvar;
    private javax.swing.JComboBox JcbCliente;
    private javax.swing.JComboBox JcbFilme;
    private javax.swing.JComboBox JcbVendedor;
    private javax.swing.JRadioButton JrbCheque;
    private javax.swing.JRadioButton JrbCredito;
    private javax.swing.JRadioButton JrbDebito;
    private javax.swing.JRadioButton JrbDinheiro;
    private javax.swing.JTextField JtfTroco;
    private javax.swing.JTextField JtfValorPago;
    private javax.swing.JTextField JtfValorTotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLocacao;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getJbtCancelar() {
        return JbtCancelar;
    }

    public void setJbtCancelar(javax.swing.JButton JbtCancelar) {
        this.JbtCancelar = JbtCancelar;
    }

    public javax.swing.JButton getJbtExcluir() {
        return JbtExcluir;
    }

    public void setJbtExcluir(javax.swing.JButton JbtExcluir) {
        this.JbtExcluir = JbtExcluir;
    }

    public javax.swing.JButton getJbtIncluir() {
        return JbtIncluir;
    }

    public void setJbtIncluir(javax.swing.JButton JbtIncluir) {
        this.JbtIncluir = JbtIncluir;
    }

    public javax.swing.JButton getJbtSair() {
        return JbtSair;
    }

    public void setJbtSair(javax.swing.JButton JbtSair) {
        this.JbtSair = JbtSair;
    }

    public javax.swing.JButton getJbtSalvar() {
        return JbtSalvar;
    }

    public void setJbtSalvar(javax.swing.JButton JbtSalvar) {
        this.JbtSalvar = JbtSalvar;
    }

    public javax.swing.JComboBox getJcbCliente() {
        return JcbCliente;
    }

    public void setJcbCliente(javax.swing.JComboBox JcbCliente) {
        this.JcbCliente = JcbCliente;
    }

    public javax.swing.JComboBox getJcbFilme() {
        return JcbFilme;
    }

    public void setJcbFilme(javax.swing.JComboBox JcbFilme) {
        this.JcbFilme = JcbFilme;
    }

    public javax.swing.JComboBox getJcbVendedor() {
        return JcbVendedor;
    }

    public void setJcbVendedor(javax.swing.JComboBox JcbVendedor) {
        this.JcbVendedor = JcbVendedor;
    }

    public javax.swing.JRadioButton getJrbCheque() {
        return JrbCheque;
    }

    public void setJrbCheque(javax.swing.JRadioButton JrbCheque) {
        this.JrbCheque = JrbCheque;
    }

    public javax.swing.JRadioButton getJrbCredito() {
        return JrbCredito;
    }

    public void setJrbCredito(javax.swing.JRadioButton JrbCredito) {
        this.JrbCredito = JrbCredito;
    }

    public javax.swing.JRadioButton getJrbDebito() {
        return JrbDebito;
    }

    public void setJrbDebito(javax.swing.JRadioButton JrbDebito) {
        this.JrbDebito = JrbDebito;
    }

    public javax.swing.JRadioButton getJrbDinheiro() {
        return JrbDinheiro;
    }

    public void setJrbDinheiro(javax.swing.JRadioButton JrbDinheiro) {
        this.JrbDinheiro = JrbDinheiro;
    }

    public javax.swing.JTextField getJtfTroco() {
        return JtfTroco;
    }

    public void setJtfTroco(javax.swing.JTextField JtfTroco) {
        this.JtfTroco = JtfTroco;
    }

    public javax.swing.JTextField getJtfValorPago() {
        return JtfValorPago;
    }

    public void setJtfValorPago(javax.swing.JTextField JtfValorPago) {
        this.JtfValorPago = JtfValorPago;
    }

    public javax.swing.JTextField getJtfValorTotal() {
        return JtfValorTotal;
    }

    public void setJtfValorTotal(javax.swing.JTextField JtfValorTotal) {
        this.JtfValorTotal = JtfValorTotal;
    }

    public javax.swing.ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(javax.swing.ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JTable getTabelaLocacao() {
        return tabelaLocacao;
    }

    public void setTabelaLocacao(javax.swing.JTable tabelaLocacao) {
        this.tabelaLocacao = tabelaLocacao;
    }




}
